repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --unsafe-fixes]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ breakpoint() calls
      - id: debug-statements
      # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Trims trailing whitespace
      - id: trailing-whitespace
      # Check for accidentally added large files
      - id: check-added-large-files
        args: [--maxkb=1000]
